import { pathToFileURL } from 'url';

export type ModuleSide = 'client' | 'server';

export interface SourceLocation {
  fsPath: string;
  /** 0-based. */
  line: number;
  /** Short label shown in the hover, e.g. `ls_banking/modules/banking/server.lua`. */
  display: string;
}

export interface ResolvedMember {
  name: string;
  kind: 'function' | 'field';
  separator: ':' | '.';
  params: string[];
  doc: string[];
  source?: SourceLocation;
  /** Set for alias members: the canonical member name. */
  aliasOf?: string;
}

export interface ResolvedModule {
  name: string;
  /** Resource providing the module. */
  resourceName: string;
  dir: string;
  sides: Partial<Record<ModuleSide, ResolvedMember[]>>;
  /** Sides that registered the module but whose loader candidates resolved to no file / no return table. */
  unresolvedSides: ModuleSide[];
}

const LUA_KEYWORDS = new Set([
  'and', 'break', 'do', 'else', 'elseif', 'end', 'false', 'for', 'function', 'goto', 'if', 'in',
  'local', 'nil', 'not', 'or', 'repeat', 'return', 'then', 'true', 'until', 'while',
]);

function localName(moduleName: string): string {
  const safe = moduleName.replace(/\W/g, '_');
  return LUA_KEYWORDS.has(safe) || /^\d/.test(safe) ? `M_${safe}` : safe;
}

function sourceLink(source: SourceLocation): string {
  return `[${source.display}:${source.line + 1}](${pathToFileURL(source.fsPath).href}#L${source.line + 1})`;
}

function signatureKey(m: ResolvedMember): string {
  return [m.kind, m.separator, m.params.join(','), m.doc.join('\n'), m.aliasOf ?? ''].join('|');
}

interface MergedMember {
  member: ResolvedMember;
  sides: ModuleSide[];
}

/** Members from both sides, merged when client and server declare the identical signature. */
function mergeSides(mod: ResolvedModule): MergedMember[] {
  const merged: MergedMember[] = [];
  for (const side of ['client', 'server'] as const) {
    for (const member of mod.sides[side] ?? []) {
      const same = merged.find((e) => e.member.name === member.name && signatureKey(e.member) === signatureKey(member));
      if (same) same.sides.push(side);
      else merged.push({ member, sides: [side] });
    }
  }
  return merged.sort((a, b) => a.member.name.localeCompare(b.member.name));
}

function emitModule(mod: ResolvedModule): string[] {
  const local = localName(mod.name);
  const merged = mergeSides(mod);
  const registeredSides = (['client', 'server'] as const).filter((s) => mod.sides[s] || mod.unresolvedSides.includes(s));
  const out: string[] = [];

  out.push(
    `---\`LS.${mod.name}\` - provided by \`${mod.resourceName}\`${mod.dir ? ` (\`${mod.dir}\`)` : ''}, available on ${registeredSides.join(' + ')}.`,
  );
  for (const side of mod.unresolvedSides) {
    out.push('---', `---No ${side} module file or \`return <table>\` was found, so the ${side} surface is unknown.`);
  }
  out.push(`---@class LSModule.${mod.name}`);
  for (const { member, sides } of merged) {
    if (member.kind === 'field') out.push(`---@field ${member.name} any ${sides.join(' + ')}`);
  }
  out.push(`local ${local} = {}`, '');

  for (const { member, sides } of merged) {
    if (member.kind !== 'function') continue;
    const header = [`\`${sides.join(' + ')}\``];
    if (member.aliasOf) header.push(`alias of \`${member.aliasOf}\``);
    if (member.source) header.push(sourceLink(member.source));
    out.push(`---${header.join(' - ')}`);
    if (member.doc.length) out.push('---', ...member.doc);
    out.push(`function ${local}${member.separator}${member.name}(${member.params.join(', ')}) end`, '');
  }

  out.push(`LS.${mod.name} = ${local}`);
  return out;
}

export function emitMetaFile(modules: ResolvedModule[]): string {
  const lines = [
    '---@meta',
    '-- Generated by the Perfect FiveM extension from LS:RegisterModule(...) calls.',
    '-- Do not edit: it is rewritten whenever a module or its resource changes.',
    '',
  ];
  for (const mod of [...modules].sort((a, b) => a.name.localeCompare(b.name))) {
    // Plain `--` header plus a blank line: a `---` line here would become part of the class docs.
    lines.push(`-- LS.${mod.name}`, '', ...emitModule(mod), '');
  }
  return lines.join('\n');
}
